import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const preview=location.pathname.endsWith('/member-preview.html');
if(location.pathname.endsWith('/member.html')||preview){
 const sb=preview?null:createClient('https://mzgnhmeydhhpzgxlgudh.supabase.co','sb_publishable_sxWDz2XL-BB5oXbPOR-1zg_XROZYWdD');
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const fmt=d=>new Date(d).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});
 let gymId=null,userId=null,target=3,workoutsThisWeek=0,bookedClasses=[];
 function mount(){const home=document.getElementById('home');if(!home||document.getElementById('memberWeekPlan'))return null;const el=document.createElement('section');el.id='memberWeekPlan';el.className='card member-week-plan';el.innerHTML='<div class="section-title"><div><div class="eyebrow">NEXT 7 DAYS</div><h3>Your training plan</h3></div><span class="tag" id="memberPlanStatus">Planning…</span></div><div id="memberPlanBody" class="member-plan-body">Building your week…</div>';const goal=document.getElementById('memberWeeklyGoal');goal?.after(el)||home.appendChild(el);return el}
 function render(classes,workouts,weeklyTarget){const body=document.getElementById('memberPlanBody'),status=document.getElementById('memberPlanStatus');if(!body)return;const plannedSessions=workouts+classes.length,remaining=Math.max(0,weeklyTarget-plannedSessions);status.textContent=remaining===0?'Week covered':remaining===1?'1 session to plan':`${remaining} sessions to plan`;status.classList.toggle('good',remaining===0);const booked=classes.slice(0,3).map(c=>`<div class="member-plan-item"><span class="member-plan-dot">✓</span><div><b>${esc(c.name||'Class')}</b><div class="muted">${esc(fmt(c.starts_at))} · booked</div></div></div>`).join('');const coverage=`<div class="muted member-plan-coverage">${workouts} completed · ${classes.length} booked · ${plannedSessions}/${weeklyTarget} sessions covered</div>`;const prompt=remaining?`<button class="member-plan-action" data-page="classes"><b>${remaining===1?'Plan one more session':`Plan ${remaining} more sessions`}</b><span>Browse classes and keep your weekly target on track →</span></button>`:'<div class="member-plan-complete"><b>Your week is covered.</b><span>Your completed workouts and booked classes meet your target.</span></div>';body.innerHTML=coverage+(booked||'<div class="muted">No classes booked in the next 7 days.</div>')+prompt;body.querySelector('[data-page]')?.addEventListener('click',()=>{document.querySelector('[data-page="classes"]')?.click()})}
 function renderGoalCard(){const progress=document.getElementById('memberGoalProgress'),detail=document.getElementById('memberGoalDetail'),bar=document.getElementById('memberGoalBar'),ring=document.getElementById('memberGoalRing'),message=document.getElementById('memberGoalMessage'),edit=document.getElementById('memberGoalEdit');if(!progress)return;const pct=Math.min(100,Math.round((workoutsThisWeek/target)*100));progress.textContent=`${workoutsThisWeek}/${target}`;detail.textContent=`${target} training sessions planned each week`;bar.style.width=`${pct}%`;ring.style.setProperty('--goal-progress',`${pct*3.6}deg`);message.textContent=workoutsThisWeek>=target?'Weekly goal complete. Nice work.':workoutsThisWeek===target-1?'One more session to hit your weekly goal.':`${target-workoutsThisWeek} sessions to hit your weekly goal.`;edit.textContent='Edit goal'}
 async function loadPreference(){const {data,error}=await sb.from('member_training_preferences').select('weekly_goal').eq('gym_id',gymId).eq('user_id',userId).maybeSingle();if(!error&&data?.weekly_goal)target=Math.max(1,Math.min(14,Number(data.weekly_goal)||3));else target=Math.max(1,Math.min(14,Number(localStorage.getItem('hybrid_member_weekly_goal'))||3));localStorage.setItem('hybrid_member_weekly_goal',String(target))}
 async function savePreference(value){const {error}=await sb.from('member_training_preferences').upsert({gym_id:gymId,user_id:userId,weekly_goal:value,updated_at:new Date().toISOString()},{onConflict:'gym_id,user_id'});if(error)throw error;target=value;localStorage.setItem('hybrid_member_weekly_goal',String(value));renderGoalCard();render(bookedClasses,workoutsThisWeek,target)}
 function ensureGoalDialog(){let dialog=document.getElementById('memberGoalDialog');if(dialog)return dialog;dialog=document.createElement('dialog');dialog.id='memberGoalDialog';dialog.className='member-goal-dialog';dialog.innerHTML='<form method="dialog" id="memberGoalForm"><div class="eyebrow">WEEKLY TARGET</div><h3>Set your training goal</h3><p class="muted">Choose how many training sessions you want to complete each week.</p><label for="memberGoalInput">Sessions per week</label><input id="memberGoalInput" type="number" min="1" max="14" step="1" inputmode="numeric" required><div class="member-goal-dialog-error" id="memberGoalError" role="alert"></div><div class="member-goal-dialog-actions"><button class="btn secondary" value="cancel" type="button" data-goal-cancel>Cancel</button><button class="btn primary" id="memberGoalSave" type="submit">Save goal</button></div></form>';document.body.appendChild(dialog);dialog.querySelector('[data-goal-cancel]').onclick=()=>dialog.close('cancel');dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close('cancel')});return dialog}
 function openGoalDialog(){const dialog=ensureGoalDialog(),input=dialog.querySelector('#memberGoalInput'),error=dialog.querySelector('#memberGoalError');input.value=String(target);error.textContent='';dialog.showModal();requestAnimationFrame(()=>{input.focus();input.select()})}
 function installGoalPersistence(){const dialog=ensureGoalDialog(),form=dialog.querySelector('#memberGoalForm'),save=dialog.querySelector('#memberGoalSave'),error=dialog.querySelector('#memberGoalError');document.addEventListener('click',e=>{const btn=e.target.closest?.('#memberGoalEdit');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();openGoalDialog()},true);form.addEventListener('submit',async e=>{e.preventDefault();const value=Math.round(Number(dialog.querySelector('#memberGoalInput').value));if(!Number.isFinite(value)||value<1||value>14){error.textContent='Choose a weekly goal between 1 and 14 sessions.';return}save.disabled=true;save.textContent='Saving…';error.textContent='';try{if(preview){target=value;localStorage.setItem('hybrid_member_weekly_goal',String(value));renderGoalCard();render(bookedClasses,workoutsThisWeek,target)}else{if(!gymId||!userId)throw new Error('Your member profile is not ready yet.');await savePreference(value)}dialog.close('saved')}catch(err){console.error('Could not save weekly goal',err);error.textContent='Could not save your weekly goal. Please try again.'}finally{save.disabled=false;save.textContent='Save goal'}})}
 async function init(){if(!mount())return;installGoalPersistence();if(preview){target=Math.max(1,Math.min(14,Number(localStorage.getItem('hybrid_member_weekly_goal'))||3));workoutsThisWeek=2;bookedClasses=[{name:'Early Engine',starts_at:new Date(Date.now()+86400000).toISOString()}];render(bookedClasses,workoutsThisWeek,target);renderGoalCard();return}const {data:{user}}=await sb.auth.getUser();if(!user)return;userId=user.id;const {data:membership}=await sb.from('memberships').select('gym_id').eq('user_id',userId).in('status',['active','trial']).limit(1).maybeSingle();if(!membership?.gym_id)return;gymId=membership.gym_id;await loadPreference();const now=new Date(),to=new Date(Date.now()+7*86400000),monday=new Date(now);monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));const [{data:classes},{count:legacyWorkouts,error:legacyError},{count:v2Workouts,error:v2Error}]=await Promise.all([sb.rpc('member_class_schedule',{p_gym_id:gymId,p_from:now.toISOString(),p_to:to.toISOString()}),sb.from('workout_sessions').select('id',{count:'exact',head:true}).eq('gym_id',gymId).eq('user_id',userId).gte('performed_at',monday.toISOString()),sb.from('workout_assignments').select('id',{count:'exact',head:true}).eq('gym_id',gymId).eq('member_user_id',userId).eq('status','completed').gte('completed_at',monday.toISOString())]);bookedClasses=(classes||[]).filter(x=>x.is_booked);workoutsThisWeek=(legacyError?0:(legacyWorkouts||0))+(v2Error?0:(v2Workouts||0));render(bookedClasses,workoutsThisWeek,target);renderGoalCard()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
}
