import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const preview=location.pathname.endsWith('/member-preview.html');
if(location.pathname.endsWith('/member.html')||preview){
 const sb=preview?null:createClient('https://mzgnhmeydhhpzgxlgudh.supabase.co','sb_publishable_sxWDz2XL-BB5oXbPOR-1zg_XROZYWdD');
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const fmt=d=>new Date(d).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});
 function mount(){const home=document.getElementById('home');if(!home||document.getElementById('memberWeekPlan'))return null;const el=document.createElement('section');el.id='memberWeekPlan';el.className='card member-week-plan';el.innerHTML='<div class="section-title"><div><div class="eyebrow">NEXT 7 DAYS</div><h3>Your training plan</h3></div><span class="tag" id="memberPlanStatus">Planning…</span></div><div id="memberPlanBody" class="member-plan-body">Building your week…</div>';const goal=document.getElementById('memberWeeklyGoal');goal?.after(el)||home.appendChild(el);return el}
 function render(classes,workouts,target){const body=document.getElementById('memberPlanBody'),status=document.getElementById('memberPlanStatus');if(!body)return;const remaining=Math.max(0,target-workouts);status.textContent=remaining===0?'Goal covered':remaining===1?'1 session to plan':`${remaining} sessions to plan`;status.classList.toggle('good',remaining===0);const booked=classes.slice(0,3).map(c=>`<div class="member-plan-item"><span class="member-plan-dot">✓</span><div><b>${esc(c.name||'Class')}</b><div class="muted">${esc(fmt(c.starts_at))} · booked</div></div></div>`).join('');const prompt=remaining?`<button class="member-plan-action" data-page="classes"><b>${remaining===1?'Plan one more session':`Plan ${remaining} more sessions`}</b><span>Browse classes and keep your weekly target on track →</span></button>`:'<div class="member-plan-complete"><b>Your weekly target is covered.</b><span>Anything extra is a bonus.</span></div>';body.innerHTML=(booked||'<div class="muted">No classes booked in the next 7 days.</div>')+prompt;body.querySelector('[data-page]')?.addEventListener('click',()=>{document.querySelector('[data-page="classes"]')?.click()})}
 async function init(){if(!mount())return;if(preview){render([{name:'Early Engine',starts_at:new Date(Date.now()+86400000).toISOString()}],2,3);return}const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data:membership}=await sb.from('memberships').select('gym_id').eq('user_id',user.id).in('status',['active','trial']).limit(1).maybeSingle();if(!membership?.gym_id)return;const gym=membership.gym_id,now=new Date(),to=new Date(Date.now()+7*86400000),monday=new Date(now);monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));const target=Math.max(1,Math.min(14,Number(localStorage.getItem('hybrid_member_weekly_goal'))||3));const [{data:classes},{count:workouts}]=await Promise.all([sb.rpc('member_class_schedule',{p_gym_id:gym,p_from:now.toISOString(),p_to:to.toISOString()}),sb.from('workout_sessions').select('id',{count:'exact',head:true}).eq('gym_id',gym).eq('user_id',user.id).gte('performed_at',monday.toISOString())]);render((classes||[]).filter(x=>x.is_booked),workouts||0,target)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
}
